# Importing Libraries:


In [ ]:
import numpy as np
import pandas as pd

# Reading the data:


In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
data.shape

(5572, 5)

In [ ]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1, inplace=True)
data.shape

(5572, 2)

# Splitting the data:

In [ ]:
# split the data
# 80% of the data will be in training data  20% of the data will be in testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size = 0.2)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457,)
(4457,)
(1115,)
(1115,)


# initialising count vectorizer

In [ ]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# creating an object for countvectorizer
count_vect = CountVectorizer()

# To get the feature names:

In [ ]:
# generate the word counts for the words in the documents
word_count_vector = count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '087012373

# Transforming the data:

In [ ]:
doc_array = word_count_vector.transform(x_train)
doc_array

<4457x7773 sparse matrix of type '<class 'numpy.int64'>'
	with 59282 stored elements in Compressed Sparse Row format>

In [ ]:
# converting to a array
doc_array = word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Specifying column names

In [ ]:
# converting the array into a dataframe
pd.DataFrame(doc_array)

0     1     2     3     4     5     6     7     8     9     ...  7763  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4452     0     0     0     0     0     0     0     0     0     0  ...     0   
4453     0     0     0     0     0     0     0     0     0     0  ...     0   
4454     0     0     0     0     0     0     0     0     0     0  ...     0   
4455     0     0     0     0     0     0     0     0     0     0  ...     0   
4456     0     0     0     0     0     0     0     0     0     0  ...     0   

      7764  7765  7766  7767  7768  7769  7770  7771  7772  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4452     0     0     0     0     0     0     0     0     0  
4453     0     0     0     0     0     0     0     0     0  
4454     0     0     0     0     0     0     0     0     0  
4455     0     0     0     0     0     0     0     0     0  
4456     0     0     0     0     0     0     0     0     0  

[4457 rows x 7773 columns]

In [ ]:
feature_matrix = pd.DataFrame(doc_array,columns= word_count_vector.get_feature_names())
feature_matrix

00  000  008704050406  0089  0121  01223585236  01223585334  0125698789  \
0      0    0             0     0     0            0            0           0   
1      0    0             0     0     0            0            0           0   
2      0    0             0     0     0            0            0           0   
3      0    0             0     0     0            0            0           0   
4      0    0             0     0     0            0            0           0   
...   ..  ...           ...   ...   ...          ...          ...         ...   
4452   0    0             0     0     0            0            0           0   
4453   0    0             0     0     0            0            0           0   
4454   0    0             0     0     0            0            0           0   
4455   0    0             0     0     0            0            0           0   
4456   0    0             0     0     0            0            0           0   

      02  0207  ...  ìï  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  ûò  
0      0     0  ...   0   0   0         0    0    0     0   0        0   0  
1      0     0  ...   0   0   0         0    0    0     0   0        0   0  
2      0     0  ...   0   0   0         0    0    0     0   0        0   0  
3      0     0  ...   0   0   0         0    0    0     0   0        0   0  
4      0     0  ...   0   0   0         0    0    0     0   0        0   0  
...   ..   ...  ...  ..  ..  ..       ...  ...  ...   ...  ..      ...  ..  
4452   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4453   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4454   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4455   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4456   0     0  ...   0   0   0         0    0    0     0   0        0   0  

[4457 rows x 7773 columns]

In [ ]:
# TFIDF Vectorizer
# Import TfIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and object for the TFIDF Vectorizer
tfidf = TfidfVectorizer()

In [ ]:
# apply the tfidf to the data(x_train)
x_train_transformed = tfidf.fit_transform(x_train)
x_train_transformed

<4457x7773 sparse matrix of type '<class 'numpy.float64'>'
	with 59282 stored elements in Compressed Sparse Row format>

In [ ]:
x_test_transformed = tfidf.transform(x_test)
x_test_transformed

<1115x7773 sparse matrix of type '<class 'numpy.float64'>'
	with 13660 stored elements in Compressed Sparse Row format>

In [ ]:
# Feature Names
tfidf.get_feature_names()

['00',
 '000',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '087012373

# Vocabulary Position:

In [ ]:
# position of the words in the sparse matrix
tfidf.vocabulary_

{'free': 2994,
 'message': 4479,
 'jamster': 3798,
 'get': 3124,
 'the': 6849,
 'crazy': 2057,
 'frog': 3029,
 'sound': 6376,
 'now': 4864,
 'for': 2946,
 'poly': 5324,
 'text': 6820,
 'mad1': 4324,
 'real': 5639,
 'mad2': 4325,
 'to': 6964,
 '88888': 705,
 'sounds': 6377,
 'just': 3886,
 'gbp': 3103,
 'week': 7453,
 '16': 318,
 'only': 4973,
 'apply': 1015,
 'msg': 4638,
 'ringtone': 5824,
 'from': 3030,
 'http': 3539,
 'tms': 6960,
 'widelive': 7525,
 'com': 1897,
 'index': 3665,
 'wml': 7581,
 'id': 3593,
 '1b6a5ecef91ff9': 330,
 '37819': 455,
 'first': 2877,
 'true18': 7068,
 '0430': 15,
 'jul': 3874,
 '05': 16,
 'no': 4819,
 'nokia': 4828,
 'tone': 6988,
 'ur': 7223,
 'mob': 4565,
 'every': 2672,
 'txt': 7111,
 'nok': 4827,
 '87021': 687,
 '1st': 339,
 'so': 6321,
 'txtin': 7115,
 'and': 956,
 'tell': 6787,
 'friends': 3014,
 '150p': 307,
 'reply': 5755,
 'hl': 3452,
 '4info': 520,
 'should': 6158,
 'head': 3375,
 'straight': 6541,
 'there': 6864,
 'or': 5004,
 'what': 7490,
 'tha

In [ ]:
# Idf of the terms
tfidf.idf_

array([7.09987042, 6.31141306, 8.30384323, ..., 8.70930833, 8.70930833,
       7.61069604])

In [ ]:
# Apply the naive Bayes Algorithm
# Import BernNB
from sklearn.naive_bayes import BernoulliNB
# creating an object for BerNB
model_BernNB = BernoulliNB()

In [ ]:
# Applying the algorithm to the data
# objectName.fit(Input,Output)
model_BernNB.fit(x_train_transformed, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
# prediction on test data
# SYNTAX: objectname.predict(InputValues)
y_test_pred = model_BernNB.predict(x_test_transformed)

In [ ]:
# compare the actual values(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)

array([[966,   0],
       [ 22, 127]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       966
        spam       1.00      0.85      0.92       149

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



# Testing for new message

In [ ]:
# test a single message --> Spam or Ham
new_message = pd.Series('Last few days to collect the free entry passes with 40% discount')
#calculate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [ ]:
# predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')