### Modules --> predefined,user-defined
 1. pre-defined-->math,os,random,string,statistics
 2. user-defined
  - modules
  - we use user-defined
### The different ways of importing modules
1. import modules
2. import modules as alias_name
3. from module import...
4. from modules import

###  Difference Between Python list and Numpy Array
1. less memory
2. fast
3. Covenient

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a.ndim

1

In [0]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9],[23,4,5]])
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [23,  4,  5]])

In [0]:
a1.ndim

2

In [0]:
a.shape

(9,)

In [0]:
a2=a1.reshape(-1)

In [0]:
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [23,  4,  5]])

In [0]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 23,  4,  5])

In [0]:
a2 = np.array([1,2,3])
a2

array([1, 2, 3])

In [0]:
a3=np.append(a2,[12,3,4,5,6,7,89])
a3

array([ 1,  2,  3, 12,  3,  4,  5,  6,  7, 89])

### slicing:

In [0]:
print(a1[1,2])

6


In [0]:
print(a3[3])

45


In [0]:
print(a1[1,2])

6


In [0]:
print(a1[2:,:])

[[ 7  8  9]
 [23  4  5]]


In [0]:
print(a1[2:,0:2])

[[ 7  8]
 [23  4]]


In [0]:
print(a1[0,0:2])

[1 2]


In [0]:
print(a1[0::2,:])

[[1 2 3]
 [7 8 9]]


In [0]:
print(a1[0:4,1:2])

[[2]
 [5]
 [8]
 [4]]


### iterate through array:

In [0]:
for row in a2:
    print(row)

1
2
3
4
5
6
7
8
9


In [0]:
list1 = [1,2,3,4]
for i in list1:
    print(i)

1
2
3
4


In [0]:
list1 = [[1,2],[3,4]]
for i in list1:
    print(i)

[1, 2]
[3, 4]


In [0]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 

In [0]:
np.array(a2.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Indexing with boolean array

In [0]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [0]:
result = (arr1 % 2 ==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [0]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending Array

In [0]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [0]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))#vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [0]:
print(np.hstack((arr1,arr2)))#horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [0]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [0]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions
1. zeros()
2. ones()
3. eye()
4. full()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [0]:
z = np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [0]:
o = np.ones((3,3),c
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
f = np.full((2,2),"shresta")
print(f)

[['shresta' 'shresta']
 ['shresta' 'shresta']]


In [0]:
#eye()
e = np.eye((3),dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [0]:
#linspace()-->linear spacing elements
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [0]:
a = np.arange(1,13,2)#range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [0]:
a = a.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [0]:
#ravel()-->flatness your array elements
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


In [0]:
### Functions:
1. min()
2. max()
3. sum()
4. sqrt()
5. std()
6. mean() 
7. median()

In [0]:
print(a.min())
print(a.max())

1
11


In [0]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [0]:
print(a.sum())#sum of all the elements
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of column elements

36
[ 9 27]
[ 8 12 16]


In [0]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [0]:
np.mean(a)

6.0

In [0]:
np.median(a)

6.0

In [0]:
np.std(a)#standard deviation

3.415650255319866

### Mathematical Operations: +,-,*,/,%

In [0]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


### dot--> Matrix multiplication
### arr1 = m Xn
### arr2 = n X i


In [0]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [0]:
#Transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying user - defined function:

In [0]:
list1 = list(range(1,20))
list1 


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [0]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [0]:
#1/(1+1) -->x/(x+1)
result = [x/(x+1)for x in list1]
result

In [0]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [0]:
lambda x : x/(x+1)

In [0]:
help(np.linalg)

In [0]:
help(np.random)