In [0]:
from numpy import random
print(random.randint(1,100))#random integer in given range
print(random.rand())#float no btw 0-1

76
0.2962725180950383


In [0]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[50 63 67]
[[85 48  7 38]
 [38 75 80 36]
 [54 64 12 62]]
[[[18 12]
  [87 86]
  [41 65]
  [89 59]]

 [[19 19]
  [25 83]
  [72 95]
  [40 91]]

 [[84 80]
  [94 67]
  [23 11]
  [77 88]]]


In [0]:
##creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

In [0]:
a = random.randint(100,size=(3))
a                  

array([64, 45, 70])

In [0]:
random.choice(a)

45

In [0]:
#single element will be selected
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 4, 2, 4],
       [2, 2, 4, 4],
       [1, 5, 1, 4],
       [2, 1, 3, 3]])

In [0]:
#for generating array withe given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[2, 4, 5, 5],
       [3, 5, 1, 5],
       [5, 3, 2, 5],
       [4, 3, 3, 5]])

### pandas:
1. Data manipulation,analysis and cleaning
2. Tabular,unlabeled

### Creating a Data Frame
1. using 2 dictionaries
2. simple dictonary -->Data frame
3. using series 

In [0]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [0]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'f':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data)
df

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [0]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the Data Frame:
1. loc
2. iloc


In [0]:
type(df3)

pandas.core.frame.DataFrame

In [0]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [0]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [0]:
#single
df3.loc[:,"column1",]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
#extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [0]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [0]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [0]:
df3.shape

(10, 3)

In [0]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [0]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from Data Frame:
1. head()
2. tail()
3. sample()

In [0]:
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [0]:
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [0]:
df3.sample()

column1  column2 column3
6        7    34.45       g

In [0]:
df3.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [0]:
df3.sample(2)

column1  column2 column3
0        1    12.23       a
6        7    34.45       g

In [0]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [0]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [0]:
#rnaming the column headers
df3 = df3.rename(columns={"column1":"First",
           "column2":"Second",
           "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j

In [0]:
df3.rename(columns={"column1":"First",
           "column2":"Second",
           "column3":"Third"},inplace=True)
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j